name: docs

on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install sphinx
      run: |
        pip3 install --upgrade pip
        sudo apt install python3-setuptools
        pip3 install furo==2020.10.5b9
        pip3 install jinja2
        pip3 install sphinx-copybutton
    
    - name: Install manim env
      run: |
        pip3 install -r requirements.txt
    
    - name: Build document with Sphinx
      run: |
        cd docs
        export PATH="$PATH:/home/runner/.local/bin"
        export SPHINXBUILD="python3 -m sphinx"
        make html
        
    - name: Deploy to GitHub pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.DOC_DEPLOY_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/build/html